jobs:
  # Drive in and unload
  - priority: 1
    map_id: "map"
    scheduled_time: 0.0 #delta time in s from start
    deadline: 90000.0 #delta time in s from start
    agv_assignment:
      uuid: "000000000cob4_18"
    actions:
      - type: 1
        parameters:
          - key: target_pose
            value: crossing_right_in
          - key: use_pd
            value: "False"
      - type: 8
        parameters:
          - key: signal
            value: "cob4-18"
          - key: conditions
            value:  "raw3-3"
      - type: 1
        parameters:
          - key: target_pose
            value: cable_pick
          - key: use_pd
            value: "True"
          - key: priority
            value: "90"
      - type: 2 # dock
        parameters:
          - key: station
            value: station_cable_drop
      - type: 5 # unload
        parameters: {}
      - type: 3 # undock
        parameters:
          - key: station
            value: station_cable_drop
  # Leave and wait
  - priority: 1
    map_id: "map"
    scheduled_time: 10.0 #delta time in s from start
    deadline: 40.0 #delta time in s from start
    agv_assignment:
      uuid: "000000000cob4_18"
    actions:
      - type: 1
        parameters:
          - key: target_pose
            value: stairs
          - key: use_pd
            value: "False"
      - type: 8
        parameters:
          - key: signal
            value: "cob4-18"
          - key: conditions
            value: "raw3-3"
      - type: 1
        parameters:
          - key: target_pose
            value: stacking_under_museum
          - key: use_pd
            value: "False"
      - type: 8
        parameters:
        - key: duration
          value: "7"
      - type: 1
        parameters:
          - key: target_pose
            value: crossing_right_in
          - key: use_pd
            value: "False"


  # drive in
  - priority: 1
    map_id: "map"
    scheduled_time: 0.0 #delta time in s from start
    deadline: 90000.0 #delta time in s from start
    agv_assignment:
      uuid: "0000000000raw3_3"
    actions:
      - type: 1
        parameters:
          - key: target_pose
            value: open_lab_raw_start
          - key: use_pd
            value: "False"
      - type: 8
        parameters:
          - key: signal
            value: "raw3-3"
          - key: conditions
            value: "cob4-18"
      - type: 1
        parameters:
          - key: target_pose
            value: cable_drop
          - key: use_pd
            value: "True"
          - key: priority
            value: "30"
      - type: 2 #dock
        parameters:
          - key: station
            value: station_cable_pick
      - type: 4 #load
        parameters: {}
      - type: 3 # undock
        parameters:
          - key: station
            value: station_cable_pick

  # drive out
  - priority: 1
    map_id: "map"
    scheduled_time: 10.0 #delta time in s from start
    deadline: 40.0 #delta time in s from start
    agv_assignment:
      uuid: "0000000000raw3_3"
    actions:
      - type: 1
        parameters:
          - key: target_pose
            value: stacking_under_museum
          - key: use_pd
            value: "False"
      - type: 8
        parameters:
        - key: duration
          value: "5"
      - type: 8
        parameters:
          - key: signal
            value: "raw3-3"
          - key: conditions
            value: "cob4-18"
      - type: 1
        parameters:
          - key: target_pose
            value: open_lab_raw_start
          - key: use_pd
            value: "False"

cycle_time: 9000000.0

positions:
  open_lab_raw_start: {x: 28.3, y: 19.8, yaw: 3.14}
  crossing_left_in: {x: 26.771, y: 24.186, yaw: -1.605}
  crossing_right_in: {x: 26.641, y: 16.923, yaw: 1.544}
  crossing_left_out: {x: 26.771, y: 24.186, yaw: 1.544}
  crossing_right_out: {x: 26.641, y: 16.923, yaw: -1.605}
  charging_pose: {x: 28.25, y: 20.3, yaw: 0.0}
  start_pose_cob: {x: 28.25, y: 20.3, yaw: 3.14}
  cable_pick: {x: 18.6, y: 24.0, yaw: 3.14}
  cable_drop: {x: 18.46, y: 19.78, yaw: 3.14}
  cable_pick_exit: {x: 19.6, y: 24.0, yaw: 0.0}
  cable_drop_exit: {x: 19.46, y: 19.78, yaw: 0.0}
  griff_in_die_kiste: {x: 39.685, y: 27.003, yaw: -1.611}
  door: {x: 16.526, y: 28.931, yaw: -0.041}
  stairs: {x: 12.56,y: 12.88,yaw: 1.549}
  stacking: {x: 33.39, y: 14.88, yaw: 1.531}
  stacking_under_museum: {x: 22.0, y: 12.0, yaw: -1.531}
