jobs:
  - priority: 1
    map_id: "map"
    scheduled_time: 0.0 #delta time in s from start
    deadline: 90000.0 #delta time in s from start
    agv_assignment:
      uuid: "0000000000raw4_0"
    actions:
      - type: 1
        parameters:
          - key: target_pose
            value: start_pose
      - type: 1
        parameters:
          - key: target_pose
            value: dock_pose
      - type: 4
        parameters: {}
      - type: 1
        parameters:
          - key: target_pose
            value: middle_pose
      - type: 1
        parameters:
          - key: target_pose
            value: start_pose

cycle_time: 9.0

positions:
  start_pose: {x: -0.25, y: 0.015, yaw: -0.062}
  middle_pose: {x: 0.30, y: 0.015, yaw: -0.062}
  dock_pose: {x: 1.07 , y: 0.015, yaw: -0.100}
  #dock_pose: {x: 0.89 , y: 0.015, yaw: 0.004}
